<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxlfcbb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxlfcbb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPxlfcbb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPxlfcbb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPxlfcbb\appProdProjectContainer([
    'container.build_hash' => 'Pxlfcbb',
    'container.build_id' => '05c318d2',
    'container.build_time' => 1625699617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxlfcbb');
